### ISSUE TITLE
Add cloud provider attributes

### ISSUE THREAD

**Issue by ryan-levell-twc** [seleniumkit/sctl#4]
I tried to use `username` and `password` but they are ignored when I run `./sctl --dryRun`
```
{
  "hosts":{
    "cloud":{
      "cloud-provider-1":{
        "cloud.com":{
          "port":4444,
          "count":1,
          "username": "user1",
          "password": "12345"
        }
      }
    }
  ...
```

Actual
```
<host name="cloud.com" port="4444" count="1"></host>
```

Desired
```
<host name="cloud.com" port="4444" count="1" username="user1" password="12345"></host>
```

@vania-pooh  I am sure you'll beat me to this issue, but started some Go tutorials today to possibly contribute.

**Comment by vania-pooh** [comment]
@ryan-levell-twc no this seems to be a reasonable idea. This is not present because we have never needed it and because `sctl` was created before this feature appeared in Ggr. So I can either implement it myself or wait for your PR and help to deliver good Golang code (as you wish).

**Comment by ryanlevell** [comment]
I am trying to build the project and on step 2:
> Download dependencies: $ godep restore

```

$ git clone https://github.com/seleniumkit/sctl.git
Cloning into 'sctl'...
remote: Counting objects: 77, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 77 (delta 0), reused 4 (delta 0), pack-reused 73
Unpacking objects: 100% (77/77), done.
Checking connectivity... done.

$ cd sctl/

$ godep restore
godep: open Godeps/Godeps.json: no such file or directory
```
Do you know how I can resolve this?

Also, should I be executing `go get github.com/seleniumkit/sctl` rather than `git clone https://github.com/seleniumkit/sctl.git` (step 1)?

**Comment by vania-pooh** [comment]
@ryan-levell-twc ah, I forgot to change README.md. We recently migrated to [dep](https://github.com/golang/dep). You need to install it and then type:
```
$ dep ensure
```
Will update README after merging your PR.

**Comment by vania-pooh** [comment]
And yes, you should normally `go get` the source. However to push I'm always changing remote URL from `HTTPS` to `git`.

**Comment by ryanlevell** [comment]
Thanks for the info!

**Comment by vania-pooh** [comment]
@ryan-levell-twc thank you for contribution. You changes should be now available in Docker container: `seleniumkit\sctl:latest`. Or you could build master (I squashed commits for clean history). Please check whether it works for you and I could release these changes.

**Comment by ryanlevell** [comment]
No problem, thanks for letting me help. `seleniumkit/sctl:latest` is working as expected for me.

**Comment by vania-pooh** [comment]
https://github.com/seleniumkit/sctl/releases/tag/1.1.0
